# Generated by Django 3.0.8 on 2020-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20200711_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='Download.png', null=True, upload_to=''),
        ),
    ]
